config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :departments

  root 'students#index'
  
  resources :students
  get 'changestatus/:stid' => 'students#changestatus'
  
  get '/welcome' => 'students#welcome'
  get '/second' => 'students#second'

end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :department
    before_save :name_caps 
    before_create :updatestatus
    after_commit :success_msg
    belongs_to :user

    validates :name, presence: true
    validates :department_id, presence: true

    validate :body_length 







    def body_length
    errors.add(:base, "Your description has exceeded the limit capacity") if desc.length >20
    end
    
    protected
	def name_caps
      self.name = name.capitalize
    end
    def updatestatus
      self.status = "Active"
    end
    def success_msg
    puts "We have saved record."
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :students
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:domain, :desc)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def welcome
     @var = 6
    end

    def second
     @var = 6
     @var2 = params[:id].to_i + 4
     #<!--<%= link_to "Pass Link", {:controller => 'tests' , :action => 'calc' , :id => 4 } %> | -->
    end
   
   def index
    
   	@stud = Student.all.order(created_at: :desc).where(:user_id => current_user.id)

   end


   def show
    @row = Student.find(params[:id])
   end

    def new
	 # @stud = Student.new
		#@category = Category.all
    @stud = current_user.students.build
    end

    def create
      #@stud = Student.new(test_params)
      
    @stud = current_user.students.build(test_params)
      
		if @stud.save
			#render :action => :index
			redirect_to students_path
      flash.now[:info] = "Here are your all records from DB"

		else
			render "new"
		end
    end

     def edit
       @stud = Student.find(params[:id])
     end

     def update
    @stud = Student.find(params[:id])

    if @stud.update_attributes(test_params)
      redirect_to root_path, :notice => "The Post is updated"

    else
      render "edit"
    end
    end


    def destroy
    @stud = Student.find(params[:id])
    @stud.destroy
    redirect_to students_path, :notice => "The Post is deleted"

    end
 # Code to actiate or deactivate a student
    def changestatus
     @stud = Student.find(params[:stid])
     if @stud.status == "Active"
       @stud.status= "Inactive"
       @stud.save
       redirect_to root_path
     else
       @stud.status= "Active"
       @stud.save
       redirect_to root_path
     end
    end

  private
  def test_params
      params.require(:student).permit(:id,:name,:age,:dob,:above18,:desc,:department_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def loginuser
      User.find(current_user).email
	end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper

	def checkadmin
		@user = User.find(current_user).roles
     if @user == "Admin"
       return @user
     else
     	return false
     end
	end
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Departments</h1>

<table>
  <thead>
    <tr>
      <th>Domain</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.domain %></td>
        <td><%= department.desc %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Domain:</strong>
  <%= @department.domain %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @department.desc %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/layouts/_header.html.erb

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Teaching", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">


   <% if user_signed_in? %>
      <li><%= link_to "Students", students_path %></li>
      <li><%= link_to "Departments", departments_path %></li>      
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <li><%=link_to "Logged in as #{loginuser}","#"%></li>
              
  <% else %>
      <li><%= link_to "Log in", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
  <% end %>

  </ul>
    </nav>

  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
<div class="container">

<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>
</div>
</body>
</html>

app/views/students/edit.html.erb

<h1> This is Edit post</h1>

<div id="subbut"> This is where you enter records</div>

<%= form_for @stud do |f| %>
 <% if @stud.errors.any? %>
 <div id="error_explanation">
      <h2><%= pluralize(@stud.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @stud.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

	<p> 
		<%= f.label :name %>
		<%= f.text_field :name %></br> <br>
    <%= f.label :age%> 
    <%= f.number_field :age%><br><br>
    <%= f.label :dob%> 
    <%= f.date_field :dob %></br><br>
    <%= f.label :above18 %>
    <%= f.select :above18, ['True', 'False'] %><br><br>
    <%= f.label :desc %>
    <%= f.text_area :desc%></br><br>

	</p>

    <p>
      <div id="subbut">
    	<%= f.submit "Update" %>
    </div>
    </p>

    <% end %>
    <br>
    <%= link_to "Home", students_path %>


app/views/students/index.html.erb
This is our index page

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      
      <th>Date of Birth</th>
      <th>Above18</th>
       <th>Department</th>
      <th>Created At</th>
       <th>Modify</th>
       <th>Remove</th>
       <% if checkadmin %>
       <th>Status</th>
       <%end%>
       
    </tr>
  </thead>
  <tbody>
<% @stud.each do |row| %>
<tr>
  <td> <%= link_to row.name ,{:controller => 'students' , :action => 'show', :id => row.id} %></td>
<td><%=  row.age %></td>
<td><%=  row.dob %></td>
<td><%=  row.above18 %></td>
<td><%=  row.department.domain %></td>
<td><small><%= row.created_at.strftime("%b %d. %Y") %></small></br></td>
<td><%= link_to "Edit", {:controller => 'students' , :action => 'edit', :id => row.id} %></td>
<td><%= link_to 'Destroy', row, data:{confirm: 'Are you sure to delete'} , method: :delete %></td>
<td><% if checkadmin %>
<%=  row.status %>|<%= link_to 'Change', {:controller => 'students' , :action => 'changestatus', :stid => row.id} %>
<%end%>
</td>

</tr>
<% end %>
  </tbody>
    </table><br>
    <%= link_to "Add Student", new_student_path %>
    <%= link_to "Add Departments", new_department_path %>

app/views/students/new.html.erb

<h3> This is New post</h3>
<%= form_for @stud do |f| %>
 <% if @stud.errors.any? %>
 <div id="error_explanation">
      <h2><%= pluralize(@stud.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @stud.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
	<p> 
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
    <%= f.label :age%> 
    <%= f.number_field :age , class: 'form-control'%>
    <%= f.label :dob%> 
    <%= f.date_field :dob , class: 'form-control' %>
    <%= f.label :above18 %>
    <%= f.select :above18, ['True', 'False'] , class: 'form-control' %><br>
    <%= f.label :department_id %> 
    <%= f.select :department_id, Department.all.collect {|x| [x.domain, x.id]}, {:include_blank => "Select One" } , class: 'form-control'%>
    <%= f.label :desc %>
    <%= f.text_area :desc , class: 'form-control'%>

	</p>

    <p>
      <div id="subbut">
    	<%= f.submit "Add Post", class: "btn btn-primary" %>
    </div>
    </p>

    <% end %>
    <br>
    <%= link_to "Home", students_path %>
</div>
</div>


app/views/students/second.html.erb
Second Page in our project
<%= @var2 %>
<br>
<%= link_to "Home" , welcome_path %>

app/views/students/show.html.erb
This is our index page

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      
      <th>Date of Birth</th>
      <th>Above18</th>
      <th>Desc</th>
      <th>Created At</th>
      <th>Updated At</th>
       <th>Modify</th>
       <th>Remove</th>
    </tr>
  </thead>
  <tbody>

<tr>
  <td> <%=@row.name%></td>
<td><%=  @row.age %></td>
<td><%=  @row.dob %></td>
<td><%=  @row.above18 %></td>
<td><%=  @row.desc %></td>
<td><small><%= @row.updated_at.strftime("%b %d. %Y") %></small></br></td>
<td><small><%= @row.created_at.strftime("%b %d. %Y") %></small></br></td>
<td><%= link_to "Edit", {:controller => 'students' , :action => 'edit', :id => @row.id} %></td>
<td><%= link_to 'Destroy', @row, data:{confirm: 'Are you sure to delete'} , method: :delete %></td>
</tr>

  </tbody>
    </table><br>
    <%= link_to "Add New", new_student_path %>

app/views/students/welcome.html.erb
<h1> Welcome Naresh to ruby on rails</h1>
<% if @var > 10 %>
<%= @var %>
<% end %>
<%= link_to "Firsts Way" , second_path %><br>
<%= link_to "Second Way", {:controller => 'students' , :action => 'second'} %></br>
<%= link_to "Value", {:controller => 'students' , :action => 'second', :id => 4} %></br>

 <%= link_to "Gmail ", "http://www.gmail.com/", data: { confirm: "Are you sure?" } %>
